Document: browserserver
Title: Debian browserserver Manual
Author: <insert document author here>
Abstract: This manual describes what browserserver is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/browserserver/browserserver.sgml.gz

Format: postscript
Files: /usr/share/doc/browserserver/browserserver.ps.gz

Format: text
Files: /usr/share/doc/browserserver/browserserver.text.gz

Format: HTML
Index: /usr/share/doc/browserserver/html/index.html
Files: /usr/share/doc/browserserver/html/*.html
