// This file is autogenerated from YapCodeGen. Do not Edit 

#ifndef BROWSERSERVERBASE_H
#define BROWSERSERVERBASE_H

#include <YapServer.h>
#include <YapProxy.h>
#include <YapPacket.h>

class BrowserServerBase : public YapServer
{
public:

    BrowserServerBase(const char* name) : YapServer(name) {}
    virtual ~BrowserServerBase() {}

    // Async Messages
    void msgPainted(YapProxy* proxy, int32_t sharedBufferKey);
    void msgReportError(YapProxy* proxy, const char* url, int32_t code, const char* msg);
    void msgContentsSizeChanged(YapProxy* proxy, int32_t width, int32_t height);
    void msgScrolledTo(YapProxy* proxy, int32_t contentsX, int32_t contentsY);
    void msgLoadStarted(YapProxy* proxy);
    void msgLoadStopped(YapProxy* proxy);
    void msgLoadProgress(YapProxy* proxy, int32_t progress);
    void msgLocationChanged(YapProxy* proxy, const char* uri, bool canGoBack, bool canGoForward);
    void msgTitleChanged(YapProxy* proxy, const char* title);
    void msgTitleAndUrlChanged(YapProxy* proxy, const char* title, const char* url, bool canGoBack, bool canGoForward);
    void msgDialogAlert(YapProxy* proxy, const char* syncPipePath, const char* msg);
    void msgDialogConfirm(YapProxy* proxy, const char* syncPipePath, const char* msg);
    void msgDialogPrompt(YapProxy* proxy, const char* syncPipePath, const char* msg, const char* defaultValue);
    void msgDialogUserPassword(YapProxy* proxy, const char* syncPipePath, const char* msg);
    void msgActionData(YapProxy* proxy, const char* dataType, const char* data);
    void msgDownloadStart(YapProxy* proxy, const char* url);
    void msgDownloadProgress(YapProxy* proxy, const char* url, int32_t totalSizeSoFar, int32_t totalSize);
    void msgDownloadError(YapProxy* proxy, const char* url, const char* errorMsg);
    void msgDownloadFinished(YapProxy* proxy, const char* url, const char* mimeType, const char* tmpFilePath);
    void msgLinkClicked(YapProxy* proxy, const char* url);
    void msgMimeHandoffUrl(YapProxy* proxy, const char* mimeType, const char* url);
    void msgMimeNotSupported(YapProxy* proxy, const char* mimeType, const char* url);
    void msgCreatePage(YapProxy* proxy, int32_t identifier);
    void msgClickRejected(YapProxy* proxy, int32_t counter);
    void msgPopupMenuShow(YapProxy* proxy, const char* identifier, const char* menuDataFileName);
    void msgPopupMenuHide(YapProxy* proxy, const char* identifier);
    void msgSmartZoomCalculateResponseSimple(YapProxy* proxy, int32_t pointX, int32_t pointY, int32_t left, int32_t top, int32_t right, int32_t bottom, int32_t fullscreenSpotlightHandle);
    void msgFailedLoad(YapProxy* proxy, const char* domain, int32_t errorCode, const char* failingURL, const char* localizedDescription);
    void msgEditorFocused(YapProxy* proxy, bool focused, int32_t fieldType, int32_t fieldActions);
    void msgDidFinishDocumentLoad(YapProxy* proxy);
    void msgUpdateGlobalHistory(YapProxy* proxy, const char* url, bool reload);
    void msgSetMainDocumentError(YapProxy* proxy, const char* domain, int32_t errorCode, const char* failingURL, const char* localizedDescription);
    void msgPurgePage(YapProxy* proxy);
    void msgInspectUrlAtPointResponse(YapProxy* proxy, int32_t queryNum, bool succeeded, const char* url, const char* desc, int32_t rectWidth, int32_t rectHeight, int32_t rectX, int32_t rectY);
    void msgGetHistoryStateResponse(YapProxy* proxy, int32_t queryNum, bool canGoBack, bool canGoForward);
    void msgUrlRedirected(YapProxy* proxy, const char* url, const char* userData);
    void msgDialogSSLConfirm(YapProxy* proxy, const char* syncPipePath, const char* host, int32_t code, const char* certFile);
    void msgMetaViewportSet(YapProxy* proxy, double initialScale, double minimumScale, double maximumScale, int32_t width, int32_t height, bool userScalable);
    void msgHighlightRects(YapProxy* proxy, const char* rectsJson);
    void msgIsEditing(YapProxy* proxy, int32_t queryNum, bool isEditing);
    void msgSaveImageAtPointResponse(YapProxy* proxy, int32_t queryNum, bool succeeded, const char* filepath);
    void msgGetImageInfoAtPointResponse(YapProxy* proxy, int32_t queryNum, bool succeeded, const char* baseUri, const char* src, const char* title, const char* altText, int32_t width, int32_t height, const char* mimeType);
    void msgMakePointVisible(YapProxy* proxy, int32_t x, int32_t y);
    void msgIsInteractiveAtPointResponse(YapProxy* proxy, int32_t queryNum, bool interractive);
    void msgGetElementInfoAtPointResponse(YapProxy* proxy, int32_t queryNum, bool succeeded, const char* element, const char* id, const char* name, const char* cname, const char* type, int32_t left, int32_t top, int32_t right, int32_t bottom, bool isEditable);
    void msgCopiedToClipboard(YapProxy* proxy);
    void msgPastedFromClipboard(YapProxy* proxy);
    void msgRemoveSelectionReticle(YapProxy* proxy);
    void msgCopySuccessResponse(YapProxy* proxy, int32_t queryNum, bool success);
    void msgPluginFullscreenSpotlightCreate(YapProxy* proxy, int32_t spotlightHandle, int32_t rectX, int32_t rectY, int32_t rectWidth, int32_t rectHeight);
    void msgPluginFullscreenSpotlightRemove(YapProxy* proxy);
    void msgSpellingWidgetVisibleRectUpdate(YapProxy* proxy, int32_t rectX, int32_t rectY, int32_t rectWidth, int32_t rectHeight);
    void msgHitTestResponse(YapProxy* proxy, int32_t queryNum, const char* hitTestResultJson);
    void msgAddFlashRects(YapProxy* proxy, const char* rectsJson);
    void msgRemoveFlashRects(YapProxy* proxy, const char* rectsJson);
    void msgShowPrintDialog(YapProxy* proxy);
    void msgGetTextCaretBoundsResponse(YapProxy* proxy, int32_t queryNum, int32_t left, int32_t top, int32_t right, int32_t bottom);
    void msgUpdateScrollableLayers(YapProxy* proxy, const char* json);

protected:

    virtual void handleSyncCommand(YapProxy* proxy, YapPacket* cmd, YapPacket* reply);
    virtual void handleAsyncCommand(YapProxy* proxy, YapPacket* cmd);

    // Sync Commands
    virtual void syncCmdRenderToFile(YapProxy* proxy, const char* filename, int32_t viewX, int32_t viewY, int32_t viewW, int32_t viewH, int32_t& result) = 0;

    // Async Commands
    virtual void asyncCmdConnect(YapProxy* proxy, int32_t pageWidth, int32_t pageHeight, int32_t sharedBufferKey1, int32_t sharedBufferKey2, int32_t sharedBufferSize, int32_t identifier) = 0;
    virtual void asyncCmdSetWindowSize(YapProxy* proxy, int32_t width, int32_t height) = 0;
    virtual void asyncCmdSetUserAgent(YapProxy* proxy, const char* userAgent) = 0;
    virtual void asyncCmdOpenUrl(YapProxy* proxy, const char* url) = 0;
    virtual void asyncCmdSetHtml(YapProxy* proxy, const char* url, const char* body) = 0;
    virtual void asyncCmdClickAt(YapProxy* proxy, int32_t contentX, int32_t contentY, int32_t numClicks, int32_t counter) = 0;
    virtual void asyncCmdKeyDown(YapProxy* proxy, uint16_t key, uint16_t modifiers) = 0;
    virtual void asyncCmdKeyUp(YapProxy* proxy, uint16_t key, uint16_t modifiers) = 0;
    virtual void asyncCmdForward(YapProxy* proxy) = 0;
    virtual void asyncCmdBack(YapProxy* proxy) = 0;
    virtual void asyncCmdReload(YapProxy* proxy) = 0;
    virtual void asyncCmdStop(YapProxy* proxy) = 0;
    virtual void asyncCmdPageFocused(YapProxy* proxy, bool focused) = 0;
    virtual void asyncCmdExit(YapProxy* proxy) = 0;
    virtual void asyncCmdCancelDownload(YapProxy* proxy, const char* url) = 0;
    virtual void asyncCmdInterrogateClicks(YapProxy* proxy, bool enable) = 0;
    virtual void asyncCmdZoomSmartCalculateRequest(YapProxy* proxy, int32_t pointX, int32_t pointY) = 0;
    virtual void asyncCmdDragStart(YapProxy* proxy, int32_t contentX, int32_t contentY) = 0;
    virtual void asyncCmdDragProcess(YapProxy* proxy, int32_t deltaX, int32_t deltaY) = 0;
    virtual void asyncCmdDragEnd(YapProxy* proxy, int32_t contentX, int32_t contentY) = 0;
    virtual void asyncCmdSetMinFontSize(YapProxy* proxy, int32_t minFontSizePt) = 0;
    virtual void asyncCmdFindString(YapProxy* proxy, const char* str, bool fwd) = 0;
    virtual void asyncCmdClearSelection(YapProxy* proxy) = 0;
    virtual void asyncCmdClearCache(YapProxy* proxy) = 0;
    virtual void asyncCmdClearCookies(YapProxy* proxy) = 0;
    virtual void asyncCmdPopupMenuSelect(YapProxy* proxy, const char* identifier, int32_t selectedIdx) = 0;
    virtual void asyncCmdSetEnableJavaScript(YapProxy* proxy, bool enable) = 0;
    virtual void asyncCmdSetBlockPopups(YapProxy* proxy, bool enable) = 0;
    virtual void asyncCmdSetAcceptCookies(YapProxy* proxy, bool enable) = 0;
    virtual void asyncCmdMouseEvent(YapProxy* proxy, int32_t type, int32_t contentX, int32_t contentY, int32_t detail) = 0;
    virtual void asyncCmdGestureEvent(YapProxy* proxy, int32_t type, int32_t contentX, int32_t contentY, double scale, double rotate, int32_t centerX, int32_t centerY) = 0;
    virtual void asyncCmdDisconnect(YapProxy* proxy) = 0;
    virtual void asyncCmdInspectUrlAtPoint(YapProxy* proxy, int32_t queryNum, int32_t pointX, int32_t pointY) = 0;
    virtual void asyncCmdGetHistoryState(YapProxy* proxy, int32_t queryNum) = 0;
    virtual void asyncCmdClearHistory(YapProxy* proxy) = 0;
    virtual void asyncCmdSetAppIdentifier(YapProxy* proxy, const char* identifier) = 0;
    virtual void asyncCmdAddUrlRedirect(YapProxy* proxy, const char* urlRe, int32_t type, bool redirect, const char* userData) = 0;
    virtual void asyncCmdSetShowClickedLink(YapProxy* proxy, bool enable) = 0;
    virtual void asyncCmdGetInteractiveNodeRects(YapProxy* proxy, int32_t pointX, int32_t pointY) = 0;
    virtual void asyncCmdIsEditing(YapProxy* proxy, int32_t queryNum) = 0;
    virtual void asyncCmdInsertStringAtCursor(YapProxy* proxy, const char* text) = 0;
    virtual void asyncCmdEnableSelection(YapProxy* proxy, int32_t pointX, int32_t pointY) = 0;
    virtual void asyncCmdDisableSelection(YapProxy* proxy) = 0;
    virtual void asyncCmdSaveImageAtPoint(YapProxy* proxy, int32_t queryNum, int32_t pointX, int32_t pointY, const char* dstDir) = 0;
    virtual void asyncCmdGetImageInfoAtPoint(YapProxy* proxy, int32_t queryNum, int32_t pointX, int32_t pointY) = 0;
    virtual void asyncCmdIsInteractiveAtPoint(YapProxy* proxy, int32_t queryNum, int32_t pointX, int32_t pointY) = 0;
    virtual void asyncCmdGetElementInfoAtPoint(YapProxy* proxy, int32_t queryNum, int32_t pointX, int32_t pointY) = 0;
    virtual void asyncCmdSelectAll(YapProxy* proxy) = 0;
    virtual void asyncCmdCopy(YapProxy* proxy, int32_t queryNum) = 0;
    virtual void asyncCmdPaste(YapProxy* proxy) = 0;
    virtual void asyncCmdCut(YapProxy* proxy) = 0;
    virtual void asyncCmdSetMouseMode(YapProxy* proxy, int32_t mode) = 0;
    virtual void asyncCmdDisableEnhancedViewport(YapProxy* proxy, bool disable) = 0;
    virtual void asyncCmdIgnoreMetaTags(YapProxy* proxy, bool ignore) = 0;
    virtual void asyncCmdSetScrollPosition(YapProxy* proxy, int32_t cx, int32_t cy, int32_t cw, int32_t ch) = 0;
    virtual void asyncCmdPluginSpotlightStart(YapProxy* proxy, int32_t cx, int32_t cy, int32_t cw, int32_t ch) = 0;
    virtual void asyncCmdPluginSpotlightEnd(YapProxy* proxy) = 0;
    virtual void asyncCmdHideSpellingWidget(YapProxy* proxy) = 0;
    virtual void asyncCmdSetNetworkInterface(YapProxy* proxy, const char* interfaceName) = 0;
    virtual void asyncCmdHitTest(YapProxy* proxy, int32_t queryNum, int32_t cx, int32_t cy) = 0;
    virtual void asyncCmdSetVirtualWindowSize(YapProxy* proxy, int32_t width, int32_t height) = 0;
    virtual void asyncCmdPrintFrame(YapProxy* proxy, const char* frameName, int32_t lpsJobId, int32_t width, int32_t height, int32_t dpi, bool landscape, bool reverseOrder) = 0;
    virtual void asyncCmdTouchEvent(YapProxy* proxy, int32_t type, int32_t touchCount, int32_t modifiers, const char* touchesJson) = 0;
    virtual void asyncCmdHoldAt(YapProxy* proxy, int32_t contentX, int32_t contentY) = 0;
    virtual void asyncCmdGetTextCaretBounds(YapProxy* proxy, int32_t queryNum) = 0;
    virtual void asyncCmdFreeze(YapProxy* proxy) = 0;
    virtual void asyncCmdThaw(YapProxy* proxy, int32_t sharedBufferKey1, int32_t sharedBufferKey2, int32_t sharedBufferSize) = 0;
    virtual void asyncCmdReturnBuffer(YapProxy* proxy, int32_t sharedBufferKey) = 0;
    virtual void asyncCmdSetZoomAndScroll(YapProxy* proxy, double zoom, int32_t cx, int32_t cy) = 0;
    virtual void asyncCmdScrollLayer(YapProxy* proxy, int32_t id, int32_t deltaX, int32_t deltaY) = 0;
    virtual void asyncCmdSetDNSServers(YapProxy* proxy, const char* servers) = 0;
};

#endif // BROWSERSERVERBASE_H 
